# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!
# TODO: This format file is obsolete, consider migrating to JSON.

{ fetchNuGet }:
[
  (fetchNuGet {
    pname = "linq2db";
    version = "4.4.0";
    hash = "sha256-tr2dunAu/WALJ4e75ZGOBkxh6Z7L/m5nDSeNO9mFICg=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Ref";
    version = "7.0.20";
    hash = "sha256-OEDXXjQ1HDRPiA4Y1zPr1xUeH6wlzTCJpts+DZL61wI=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.linux-arm64";
    version = "7.0.20";
    hash = "sha256-ewal9R6o20GV0R02ylSijVFdWZAbdN8TK1PCc/ltHBQ=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.linux-x64";
    version = "7.0.20";
    hash = "sha256-vq59xMfrET8InzUhkAsbs2xp3ML+SO9POsbwAiYKzkA=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.osx-arm64";
    version = "7.0.20";
    hash = "sha256-PHBb0AuRpB8kkQvQJIJSLu5Ub/U2pYA0wMGBarUkS8o=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.osx-x64";
    version = "7.0.20";
    hash = "sha256-+MQMRFzfG2CbNJnfw0buP4VorL2yR+T4UeEBSbKSmPY=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Mvc.Razor.Extensions";
    version = "6.0.0";
    hash = "sha256-TrR4soDtsyg+czs3P0nYByalKC6g6cmdQiRnOg6NRtA=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation";
    version = "7.0.2";
    hash = "sha256-P9nqZu9f+PE0yzEy5EyF4SguebZMDeZ6sClifIOQrLo=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Razor.Language";
    version = "6.0.0";
    hash = "sha256-P0bdoAG+VBR/PuYQQN4tXhJomfXw+lArXx5UQqRoWlM=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Analyzers";
    version = "3.3.2";
    hash = "sha256-pDeaMqX7a01Hp1Qd9P/y/B2rEGAv2eIY0Ld/klBZW5g=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Common";
    version = "4.0.0";
    hash = "sha256-SfQYaC9FbN60PhSzU3iM56ZeUlb/Y2FFGEnF43/5luc=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.CSharp";
    version = "4.0.0";
    hash = "sha256-ZGE+DM8siy3DHhBQcNesEHz9bEL4at+L6Cmj24+X/dc=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Razor";
    version = "6.0.0";
    hash = "sha256-j1/Mpe9Ta+4dhoa2+Zd7BaMm6MllJfaMtZ4pX+P2cqA=";
  })
  (fetchNuGet {
    pname = "Microsoft.Data.Sqlite";
    version = "7.0.2";
    hash = "sha256-OGGEAYEPvnNW+yzH3B6sz5bXEHYehnLLGK73jI3xxKE=";
  })
  (fetchNuGet {
    pname = "Microsoft.Data.Sqlite.Core";
    version = "7.0.2";
    hash = "sha256-FW3paVHyiNNXO12PoRaxRjiYAqMW5aCKQBLqayJbN3Y=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyModel";
    version = "7.0.0";
    hash = "sha256-RDoSkuY6t/CKDFy2pjx9J+AAVg25BHHKg7WePDg0ixM=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.linux-arm64";
    version = "7.0.20";
    hash = "sha256-/20dMbO1Ft0WVhl+Lv1916Thvr4kPP9LuuX4bKE+czE=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.linux-x64";
    version = "7.0.20";
    hash = "sha256-Y1Dg8Sqhya86xD+9aJOuznT4mJUyFmoF/YZc0+5LBdc=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.osx-arm64";
    version = "7.0.20";
    hash = "sha256-MTyRTWhDmMaCsNorju/tLb0w+ssKydDX/NBFzSfqB0Q=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.osx-x64";
    version = "7.0.20";
    hash = "sha256-DdumMpP5QN0rPDsB8sjxACM13mT7Wbb0w3LaCe96twc=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Ref";
    version = "7.0.20";
    hash = "sha256-W9RU3bja4BQLAbsaIhANQPJJh6DycDiBR+WZ3mK6Zrs=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.linux-arm64";
    version = "7.0.20";
    hash = "sha256-TemMvbNrDzJVHWwxVgnNN2CnTyI6TcvvZDpF4ts6IAw=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.linux-x64";
    version = "7.0.20";
    hash = "sha256-L+WaGvoXVMT3tZ7R5xFE06zaLcC3SI7LEf4ATBkUAGQ=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.osx-arm64";
    version = "7.0.20";
    hash = "sha256-VHmF1/ObK5hxGYvm5/+pTdketHnxxcnAGK5RaTQpVqE=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.osx-x64";
    version = "7.0.20";
    hash = "sha256-yktNSySitxWbO6LjcxUuewWFMF2EbcoM2w18CqxmVlc=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "2.1.2";
    hash = "sha256-gYQQO7zsqG+OtN4ywYQyfsiggS2zmxw4+cPXlK+FB5Q=";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.bundle_e_sqlite3";
    version = "2.1.2";
    hash = "sha256-XrG1nT9TfvDI5E0icxvDR2wHqqVxs/mhRRHePOQlLB8=";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.core";
    version = "2.1.2";
    hash = "sha256-bbymML2TTQJDKZbYXoiyYJnF6mh/PjKrzDkqWhLaHaY=";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.lib.e_sqlite3";
    version = "2.1.2";
    hash = "sha256-34lJgnGvODwrjn9WTkkBIg2jzYph/ARi1QSiKedCyUo=";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.provider.e_sqlite3";
    version = "2.1.2";
    hash = "sha256-e56+FgxEHqV3SGQx0ZAqzlscPxNUPXJ8Ls9rtqET1S4=";
  })
  (fetchNuGet {
    pname = "Stub.System.Data.SQLite.Core.NetStandard";
    version = "1.0.115";
    hash = "sha256-TZEqV45YCSCYQrrPMnu64PI7oT7/2sAQV/BGqeDe9JI=";
  })
  (fetchNuGet {
    pname = "System.Collections.Immutable";
    version = "5.0.0";
    hash = "sha256-GdwSIjLMM0uVfE56VUSLVNgpW0B//oCeSFj8/hSlbM8=";
  })
  (fetchNuGet {
    pname = "System.Data.SQLite.Core";
    version = "1.0.115";
    hash = "sha256-bIVWw/dMTWwnA04hcRMVI2+ZqNtD75dAwAmTJj7F4iw=";
  })
  (fetchNuGet {
    pname = "System.Data.SQLite.Core.osx.arm64";
    version = "1.0.117";
    hash = "sha256-oE+6F69lkZjFvo/WEHnOYIRvInEUii59UiiFxyjl5U8=";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.3";
    hash = "sha256-Cvl7RbRbRu9qKzeRBWjavUkseT2jhZBUWV1SPipUWFk=";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.4";
    hash = "sha256-3sCEfzO4gj5CYGctl9ZXQRRhwAraMQfse7yzKoRe65E=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Metadata";
    version = "5.0.0";
    hash = "sha256-Wo+MiqhcP9dQ6NuFGrQTw6hpbJORFwp+TBNTq2yhGp8=";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "5.0.0";
    hash = "sha256-neARSpLPUzPxEKhJRwoBzhPxK+cKIitLx7WBYncsYgo=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding.CodePages";
    version = "4.5.1";
    hash = "sha256-PIhkv59IXjyiuefdhKxS9hQfEwO9YWRuNudpo53HQfw=";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "7.0.0";
    hash = "sha256-tF8qt9GZh/nPy0mEnj6nKLG4Lldpoi/D8xM5lv2CoYQ=";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "7.0.0";
    hash = "sha256-198zqA6NR4lGCKgpdy/ptkS0jsYRT6KUjewtfi4Fi2k=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.5.4";
    hash = "sha256-owSpY8wHlsUXn5xrfYAiu847L6fAKethlvYx97Ri1ng=";
  })
]
